CHANGELOG.md, common/djangolibs/utils.py, common/static/common/css/common.css, common/templates/common/base.html, common/templates/robots.txt, common/templates/su/is_su.html, config/local_settings.py.sample, config/settings.py, config/urls.py, requirements.txt
- Switch to use django-su as it plays nicely with OIDC.
- Add config settings to enable/disable
- Add custom template
- Only allow superusers to login as other users
- Fixes #85
=> Refactor hijack users.

core/djangoapps/project/views.py
- Set status to active when adding new user to subscriptions from add user to project page
=> Set status to active when adding new user to subscriptions

core/djangoapps/project/views.py, core/djangoapps/subscription/views.py
- Fixes #97 
- Do not allow adding/delete users from project requiring review
=> Do not allow adding/delete users from project requiring review

core/djangoapps/subscription/templates/subscription/subscription_create.html
- Put function outside of document ready function to fix initial loading of quantity field
=> Put function outside of document ready function

coldfront/core/subscription/admin.py
- Make it easier to add users to subscriptions
=> Make it easier to add users to subscriptions

coldfront/config/local_settings.py.sample, coldfront/core/subscription/models.py, coldfront/core/subscription/tasks.py, coldfront/core/subscription/utils.py
- Add functionality to run functions on subscription expire
=> Add functionality to run functions on subscription expire

coldfront/core/portal/views.py, coldfront/core/project/views.py, coldfront/core/subscription/views.py
- Show the new renewal requested status on different pages
- Show all subscriptions on the project detail page
=> Fix subs bugs

coldfront/core/subscription/views.py
- PK was being accessed before being set
- Put usertest fail statement in else statement
=> Fixed bugs

coldfront/core/project/admin.py
- Allow admin to change project PI in admin site.
=> Allow PI change in project

coldfront/core/project/forms.py
- All subscriptions selected by default when adding a new user
=> Resolves #124

coldfront/core/project/templates/project/project_archive.html, coldfront/core/project/views.py
- Expire active subscriptions when archiving project
=> Expire active subscriptions when archiving project

coldfront/core/grant/forms.py, coldfront/core/grant/views.py
- Change form chart size to match grant model char size . This caused errors form errors.
=> Fix grant bug

coldfront/core/project/admin.py
- For project review, add PI to list display field and allow searching on PI name
=> Allow project review to be searched by PI name 

coldfront/core/utils/management/commands/load_test_data.py
- make admin staff to enable ability to log in to coldfront administrator
=> make admin staff

coldfront/core/subscription/views.py, coldfront/core/utils/management/commands/load_test_data.py
=> Update test data

coldfront/core/project/views.py, coldfront/core/subscription/forms.py, coldfront/core/subscription/views.py
- Resolves #149   Give staff ability to search all users
=> Resolves #149 Give staff ability to search all users

coldfront/plugins/slurm/README.md
change sacctmgr_dump to slurm_dump
=> slurm README.md update

coldfront/plugins/freeipa/management/commands/freeipa_check.py
- The query to fetch allocations to check for removed groups was not returning
the correct results. Re-factored logic
=> Fix bug where users where not being removed from groups.

coldfront/config/local_settings.py.sample, coldfront/core/allocation/templates/allocation/allocation_add_users.html, coldfront/core/allocation/views.py, coldfront/core/project/views.py, coldfront/core/user/templates/user/login.html, coldfront/core/user/templates/user/login_form.html, coldfront/core/user/urls.py
=> Fix redirect

coldfront/core/allocation/tasks.py, coldfront/core/allocation/views.py, coldfront/core/project/templates/project/project_detail.html, coldfront/core/project/views.py
=> Fix bugs add features

coldfront/core/user/templates/user/user_list_allocations.html, coldfront/core/user/urls.py, coldfront/core/user/views.py, coldfront/templates/common/authorized_navbar.html
=> Add user allocation list

coldfront/core/allocation/templates/allocation/allocation_renew.html, coldfront/core/allocation/views.py
=> Add EULA to renewal

coldfront/core/allocation/forms.py, coldfront/core/allocation/templates/allocation/allocation_add_invoice_note.html, coldfront/core/allocation/templates/allocation/allocation_delete_invoice_note.html, coldfront/core/allocation/templates/allocation/allocation_update_invoice_note.html, coldfront/core/allocation/views.py
A couple minor HTML fixes and two changes that were preventing deletion of invoice notes.
=> Fix deletion of invoice notes

coldfront/core/publication/tests.py, coldfront/core/publication/views.py
_This is a part of a number of PRs that I'm currently working on for Andrew Keen from MSU._ 
This is a fix for #204 where some DOI entries are lacking a journal field.
=> Default to '[no journal info from DOI]' when journal info is absent

coldfront/core/project/templates/project/add_user_search_results.html
This Pull Request solves the bug of Issue #214
=> Search fix (PR to solve issue #214)

coldfront/core/user/templates/user/user_profile.html, coldfront/core/user/templates/user/user_projects_managers.html, coldfront/core/user/templates/user/user_search_results.html, coldfront/core/user/urls.py, coldfront/core/user/views.py, coldfront/templates/common/authorized_navbar.html, coldfront/templates/common/navbar_nonadmin_staff.html
_This is a part of a number of PRs that I'm currently working on for @keenandr from MSU._
This PR provides a form gated with is_staff that allows the user to input a username, search matching projects, display project and managers for that project.
Please let me know if you have any questions. Thanks!
=> List who is responsible (PI, managers) for a given user

coldfront/core/publication/templates/publication/publication_export_publications.html
=> Export feature This PR fixes Issue #226

coldfront/core/project/templates/project/project_detail.html
=> Adding sorting feature to allocations and grants #221 

coldfront/core/project/views.py
=> This commit solves issue #240

docs/pages/quickstart.md
First pull request! Simple typo fix in documentation.
=> Typo fix in quickstart.md

docs/mkdocs.yml
changed some options for mkdocs theme formatting
=> updated formatting options for documentation

CHANGELOG.md, coldfront/plugins/slurm/management/commands/slurm_dump.py
Fixes #235. Disabled resource should not show up in slurm dump.
=> Skip disabled resource.

coldfront/core/project/admin.py
=> Fix editing project users in django admin.

coldfront/core/user/utils.py
=> Fix missing local variable assignment

coldfront/core/field_of_science/tests.py, coldfront/core/test_helpers/factories.py, coldfront/core/user/tests.py
Wrote model validation testing suites for the 'Field of Science' and 'User' objects. Updated the factory_boy imports in factories.py as the existing ones did not work.
=> Added tests for the 'Field of Science' and 'User' objects

coldfront/plugins/mokey_oidc/auth.py
The groups claim can be sent over as a list. The mokey_oidc plugin
is unable to deal with that, as it assumes the input for groups
is always a string.
Only call split if the claim is a string.
=> [mokey_oidc plugin] Handle groups claim as list

coldfront/core/publication/views.py
Check-boxes on publication search list did not have any effect
=> Dont add not-selected publications

coldfront/core/project/templates/project/project_archived_list.html, coldfront/core/project/templates/project/project_list.html
it seems more user-friendly if those buttons preserve search parameters
=> Forward filter parameters between Active-Archived projects search pages

coldfront/core/allocation/signals.py, coldfront/core/allocation/views.py
Signals are now dispatched for
- allocation change request approval
=> Added signal dispatch for allocation change requests

coldfront/core/allocation/views.py
Show allocation in list view if project is New or Active not just Active.
=> allocation list view if project is New or Active

coldfront/core/project/templates/project/add_user_search_results.html
Fix select-all-allocation JS in add user to project
=> Fix minor JS issues #396

README.md
Hey all, I made a standalone repo for the starfish plugin! FASRC-specific configurations have been removed and the repo is tested for integration with the UBCCR repo master branch.
=> update README with location of standalone starfish plugin repo

coldfront/plugins/freeipa/management/commands/freeipa_check.py
=> Switch to LDAP lookup for nsaccountlock in freeipa.

coldfront/plugins/slurm/associations.py
=> Include allocations in 'pending renewal' status.

coldfront/core/allocation/templates/allocation/allocation_detail.html
Fixes #409 : Added sorting to the allocation user section in the allocation detail page.
=> Allocation Detail Page User Sorting

coldfront/core/allocation/forms.py, coldfront/core/project/forms.py
Bump first_name max length to 150
=> Adjust first_name max length

coldfront/core/allocation/views.py
Learned earlier today that the post function for the AllocationCreateView was the wrong way to add a success message - it presents the success message even when an error is present on the form. This push corrects that error. It also contains the removal of an unneeded method - the AllocationAddInvoiceNoteView had two get_context_data methods and the second one is the one that would have been in operation, so I deleted the first.
=> fix misfiring success message, remove redundant function

coldfront/core/allocation/models.py, coldfront/plugins/freeipa/management/commands/freeipa_check.py, coldfront/plugins/freeipa/management/commands/freeipa_expire_users.py
- Fix bug in freeipa unix group syncing to exclude renewal requested status
- Clean up logic in freeipa expire user sync
=> Freeipa sync bugfix

coldfront/config/plugins/ldap.py, docs/pages/config.md
Update ldap.py with auth search scope subtree capability ii
signed off
=> Update ldap.py with auth search scope subtree capability ii

docs/pages/config.md
docs: Add note about django ldap auth and certs to config.md
=> docs: Add note about django ldap auth and certs to config.md

coldfront/core/user/views.py, coldfront/core/utils/mail.py
=> Use email sender for account upgrade notifications.

coldfront/core/project/signals.py, coldfront/core/project/views.py
Add project signals to core/project views.py , signals.py
(required by project_openldap plugin - to push projects to openldap)
=> Add project signals to core/project views.py , signals.py

coldfront/plugins/freeipa/tasks.py, docs/pages/howto/allocations/statuses.md
Status was actually removed [here](https://github.com/ubccr/coldfront/blob/72dbd32fc6b680dd58af09dd13deda709d5760f2/CHANGELOG.md?plain=1#L143)
=> remove "Inactive (Renewed)" status
