config/local_settings.py.sample, extra/djangoapps/freeipa/README.md, extra/djangoapps/freeipa/search.py, extra/djangoapps/ldap_user_search/README.md
- LDAP user searching is very much schema specific so this functionality has
been moved to the freeipa app. ldap_user_search is being left as an example
only.
- Add support for Kerberos SASL/GSSAPI authenticated binds to allow email
addresses to be returned in searches.
- Limit searches to only active users.
- Update documentation
=> Refactor ldap user searching.

coldfront/core/subscription/templates/subscription/subscription_request_list.html
- Show modified instead of created data because for subscriptions being renewed it makes more sense.
=> Show modified instead of created data

coldfront/core/project/templates/project/project_detail.html
External URLs with `target="_blank"` should have either `rel="noopener"`
or `rel="noreferrer"` to prevent malicious use of `window.opener`
Refs: https://developers.google.com/web/tools/lighthouse/audits/noopener
=> [fix] Close vulnerability by adding `rel="noopener"`

coldfront/core/allocation/views.py, coldfront/core/grant/views.py, coldfront/core/project/views.py, coldfront/core/publication/views.py
When form validation fails, the method would not return a (required)
`HttpResponse`. This moves the `return` outside of the `if` statement
and pushes form validation errors to the message stack.
Refs: https://github.com/ubccr/coldfront/commit/22c0c8c9ebac62399df3029d1f9256e4db8f827f
=> [fix] Display form validation errors

coldfront/core/grant/views.py
_This is a part of a number of PRs that I'm currently working on for Andrew Keen from MSU._
The test_func method was defined, but without the UserPassesTestMixin,
Djano wasn't utilizing it.
As a result, any user could create a grant for any project, by using the
proper url (with the project primary key in the appropriate place).
Additionally, the LoginRequiredMixin was absent, allowing anyone to make
such a change.
Please let me know if you have any questions. Thanks!
=> Add missing auth mixins to GrantCreateView

coldfront/core/project/templates/project/project_detail.html
This PR solves issue #224 
Moved the research output button after the grants button. Also later moved the publication button after the grant button to maintain consistency with the page.
=> Changed the order of buttons

coldfront/core/allocation/templates/allocation/allocation_add_users.html, coldfront/core/allocation/templates/allocation/allocation_allocationattribute_delete.html, coldfront/core/allocation/templates/allocation/allocation_create.html, coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/allocation/templates/allocation/allocation_invoice_detail.html, coldfront/core/allocation/templates/allocation/allocation_list.html, coldfront/core/allocation/templates/allocation/allocation_remove_users.html, coldfront/core/grant/templates/grant/grant_delete_grants.html, coldfront/core/portal/templates/portal/center_summary.html, coldfront/core/project/templates/project/project_add_users.html, coldfront/core/project/templates/project/project_archive.html, coldfront/core/project/templates/project/project_archived_list.html, coldfront/core/project/templates/project/project_detail.html, coldfront/core/project/templates/project/project_list.html, coldfront/core/project/templates/project/project_review.html, coldfront/core/project/templates/project/project_review_email.html, coldfront/core/publication/templates/publication/publication_add_publication_search.html, coldfront/core/user/templates/user/user_profile.html, coldfront/core/user/templates/user/user_projects_managers.html
This makes the following changes:
* Add the `aria-hidden` attribute to decorative icons that were missing it.
* Add `scope` attribute to table headers that were missing it.
* Add text for elements that only had icons--Note this keeps the text hidden to all but screen readers, so there is no visual change for standard users.
* Minor HTML fixes.
Other issues:
* It's generally recommended for tables to have the `caption` element. Some accessibility scanners didn't complain (Deque's aXe) while some will flag it as an issue (ComplianceSheriff). One could add the element but hide from standard view (`<caption class="sr-only">Text</caption>`) to avoid any visual changes. Considering every table has some form of header preceding it, I would think the repetition of text could be annoying to those …
=> Accessibility fixes, minor HTML fixes

coldfront/core/project/templates/project/project_detail.html
re: Issue #248 
looks like publications query in context builder is not limited, so the user should now have access to all publications if they select this option via dropdown.
Line 123-124: core/project/views.py
```python
context['publications'] = Publication.objects.filter(
project=self.object, status='Active').order_by('-year')
```
=> View all publications option from project detail page - issue #248

coldfront/core/publication/views.py, coldfront/templates/email/allocation_expiring.txt
the variable in the code was missing an "i" in expiring_in_days. This wrong spelling was used multiple times so I just changed the right spelling in the template to expring_in_days (matching the wrong spelling of variable) to avoid making mistakes.
=> spelling error- issue #251

coldfront/core/publication/forms.py, coldfront/core/publication/templates/publication/publication_add_publication_manually.html, coldfront/core/publication/views.py, coldfront/templates/403.html
This fixes #258. Add better form validation for manual publication entry. Change to using uuid4 instead of sha256 hash for unique ids. The issue is when manually entering a publication, we do not ask for a DOI as it may not have one. As a doi uniquely identifies a publication, we simply use a randomly generated uuid4 as the unique id.
=> Fix year validation bug.

coldfront/plugins/freeipa/management/commands/freeipa_check.py
This fixes #268. When adding users to a unix group, the freeipa plugin checks a users active allocations (where they are an active user on said allocation). This commit adds a check to see if all resources for the allocation are set to inactive. If so, the user will not be added to the unix group.
=> Skip allocations to inactive resources.

coldfront/core/project/templates/project/project_detail.html, coldfront/core/project/views.py
Resolves issue #259.  The grants section of the page also has a new status column to show the status of each grant associated with a project.
=> Archived grants can be viewed on the Project Detail page

coldfront/config/core.py, coldfront/core/allocation/models.py, coldfront/core/project/templates/project/project_detail.html
Resolves #193. In the allocation section of a project, the information column for an entry will display its slurm_account_name, freeipa_group name, Cloud Account Name and/or its Cloud Storage Quota. If an entry does not have any of these attributes, its description will be used to fill out the information column instead.
=> Multiple Allocations on a project for the same resource can be differentiated

docs/pages/install.md
Hello
I think ccollins and michardson must have been from an older version so I have updated the docs to reflect the users currently in [load_test_data.py](https://github.com/Iain-S/coldfront/blob/7130334c96b263c3c48b6844b6dad6e6b811c827/coldfront/core/utils/management/commands/load_test_data.py)
=> Update docs with correct username of PI#1 and center director

coldfront/config/auth.py, coldfront/core/user/urls.py
I need to be able to configure the LOGOUT_REDIRECT_URL to perform OIDC IdP logout.
Note that the default behavior of LogoutView.as_view() is to use the LOGOUT_REDIRECT_URL (thus the change from specifying the redirect to using the default in the user/urls.py causes the redirect to use the LOGOUT_REDIRECT_URL value).
=> allow logout redirect URL to be configured

coldfront/config/database.py, docs/pages/config.md
Even thought the Django-environ [docs](https://django-environ.readthedocs.io/en/latest/) use 8458, the default PostgreSQL port number is 5432. Using this in the coldfront docs may avoid confusion.
=> Update docs and config with default Postgres port number

coldfront/core/project/templates/project/project_detail.html
Resolves issue #291. A checkbox has been added to the Project Detail template that can select all users on a project to enable/disable notifications.
=> User Notifications 'select-all' button

coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/project/templates/project/project_detail.html
Resolves issue #203. When an allocation is locked in the ColdFront Administration Portal by an admin, the allocation can no longer be renewed. When an allocation is locked, the "renew now" banners change to only show the number of days an allocation has until it expires. It says "not renewable" instead of "renew now", and is no longer clickable.
=> Prevent allocation renewal setting

coldfront/config/auth.py, coldfront/config/core.py, coldfront/config/database.py, coldfront/config/env.py, coldfront/config/settings.py
I should probably have done this as 2 PRs:
See 9a5b1d2 for the main change (setting COLDFRONT_CONFIG causes an error because `environ` had not been imported into settings.py).
I then ran flake8 on the config files and fixed most of the errors (I did not address line-length errors or any files under `config/plugins/`).
=> environ import (plus some pep8)

coldfront/core/allocation/signals.py, coldfront/core/allocation/views.py
Signals are now dispatched for
- resource allocation activation
- resource allocation deactivation
Partial ubccr#293
=> Added signal dispatch for resource allocations

docs/pages/deploy.md
Noticed this while deploying ColdFront.
=> Fix spelling in Environment Path

coldfront/core/user/templates/user/user_list_allocations.html
Typo in user_list_allocations - first name was displayed twice
=> Typo in user_list_allocations.html

coldfront/core/allocation/models.py, coldfront/core/allocation/utils.py
This adds a try/except block in generate_guauge_data_from_usage() (why
the misspelling?) to catch for divide by zero errors.  If value=0, we
set the percent used to 100% (arbitrary, but better than an exception)
=> Fix for #336 - Divide-by-zero error for Attrib value=0 and has_usage

coldfront/core/allocation/forms.py, coldfront/core/allocation/templates/allocation/allocation_change_detail.html, coldfront/core/allocation/templates/allocation/allocation_change_list.html, coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/allocation/templates/allocation/allocation_note_create.html, coldfront/core/allocation/templates/allocation/allocation_request_list.html, coldfront/core/allocation/urls.py, coldfront/core/allocation/views.py
Resolves issue #341. Added a number of features to the Allocation Request workflow that were introduced in the Allocation Change Request workflow to create a more cohesive experience. Updates include: 
Allocation detail page:
Expose button to add 'notifications' so admin can include details about allocation request
Allow 'lock/unlock' to be set here like the 'allow change requests'
Allocation request list:
Change 'Date Requested/Last Modified' to 'Last Modified'
Change 'Allocation Actions' to 'Actions'
Add 'Details' button to get to Allocation detail page
Unlink ID number as this will now be the 'Details' button
Grey out 'Activate' if allocation is new - this is because allocation attributes need to be added to new allocations before allocation is approved
Remove 'Deny' button and require …
=> Ported Allocation Change Request features to Allocation Requests

coldfront/core/allocation/models.py, docs/pages/config.md
See #334
This modifies the methods get_resources_as_string() and get_parent_resource() of the Allocation class, specifically it modifies how those routines order the resources attached to the allocation for display, etc.
The modifications cause both of these methods to order the resources by
the value of the setting ALLOCATION_RESOURCE_ORDERING.  This should be a
list ref of arguments to pass to the Django QuerySet order_by() method.  The
default value is [ '-is_allocatable', 'name' ], which means that Resources
which are allocatable (is_allocatable==Yes) will come before non-allocatable
resources, and among Resources of the same allocatability, the Resources will
be ordered by name.
This should result in get_parent_resource returning the same resource as
before (as it previously used the …
=> Allow site-level control of how Resources ordered within an Allocation

coldfront/core/allocation/forms.py, coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/allocation/views.py, coldfront/templates/email/new_allocation_change_request.txt
Resolves issue #355. 
- Justifications are now required again for any allocation change request that is submitted.
- Users (non-managers) can no longer see the date drop down in a pending allocation change request.
=> Allocation Change Flow Bug Fixes

coldfront/core/publication/views.py
but different other fields, like source or for example abbreviation changes in names etc. Instead of  meaningful info, IntegrityError is raised while Django tries to insert a new record.
get_or_create uses all fields in select, defaults are used instead for new records.
=> Fix IntegrityError when publications have same UniqeID and Project

coldfront/core/allocation/views.py, coldfront/core/project/forms.py, coldfront/core/project/views.py
Resolves issue #292
- On an active Project's detail page users are now able to view all the allocations they have access to, regardless of their current status. 
- Also fixed a minor UI bug on Allocation Detail Pages where staff users used to get active checkbox fields for the "Lock/Unlock Allocation" and "Allow Change Requests" fields. Those are now disabled for them.
=> Project Detail Page: Users can see all their allocations (regardless of status)

coldfront/core/publication/forms.py, coldfront/core/publication/views.py
Resolves issue #283
* If a publication is searched for by its ID in order to be added to a project, it will now be successfully added no matter how long its author field is.
* Publications like this will have its author field truncated down to 1024 characters.
=> Bug Fix: Publications can be added to projects no matter how many authors they have

coldfront/core/grant/forms.py, coldfront/core/grant/templates/grant/grant_report_list.html, coldfront/core/grant/views.py, coldfront/core/resource/admin.py
Resolves issue #222
- Each grant on the 'Grant Resource' page now has a checkbox that can be used to export specific resources.
- Resources can now be duplicated in the Django Admin portal through the use of a 'Save as new' button.
=> Export Specific Grants

coldfront/core/project/forms.py
Resolves issue #386 
- When a PI tries to add a user to a Project, they now can only add the user to Project allocations of the following statuses: Active, New, Renewal Requested, Payment Pending, Payment Requested, Paid
=> Bug Fix: Users can no longer be added to inactive allocations when being added to a Project

coldfront/core/allocation/views.py
Currently a user can approval an allocation on either its detail page or the 'Allocation Requests' page. The approval process now redirects a user back to the page they came from.
=> Allocation request approval redirects back to the page which it was approved

coldfront/config/plugins/slurm.py
SLURM_NOOP should be a bool. "if self.noop" resolves as true even if self.noop is "False" because it is a non-empty string. Noticed this because slurm_check was responding as NOOP even when using --sync.
=> SLURM_NOOP should be a bool

coldfront/core/allocation/forms.py
Resolved issue #395 — Prior to this, when users were added to a project and a new allocation was requested, their names showed up in the order they were added. To add some consistency and clean this up (especially for large lists of users), they are now sorted alphabetically by username.
=> User sorting alphabetical by username

coldfront/core/allocation/views.py
Resolved #379 : Fixed bug that would cause allocations that had status of 'New', 'Renewal Requested', or 'Paid' would disappear from the allocation request page when changed to a status of 'Approved'. 
Tested bug through the following:
1. Created allocation requests that had statuses of 'New', 'Renewal Requested', and 'Paid' and changed their status to 'Approved'.
2. Confirmed that these allocation requests would not appear on the allocation request page after status change.
Tested fix through the following:
1. Followed the steps for the bug testing and confirmed that these allocations remained on the allocation request page after fix was applied.
Source of bug:  AllocationRequestListView class of the views file for Allocation would only list allocations with status names of 'New', …
=> Fixed allocation request 'approved' status bug

coldfront/config/core.py, coldfront/core/allocation/views.py, coldfront/core/project/views.py, coldfront/templates/common/authorized_navbar.html, coldfront/templates/common/navbar_help.html, coldfront/templates/common/nonauthorized_navbar.html
Resolves #414 —
Now, the following occur:
- the Help button on the navbar only appears when the user specifies the center's help URL, otherwise is not present
- when removing a user from an allocation or a project, the alert reads "removed 1 user" instead of "removed 1 users"
- the default center name is HPC Center to avoid redundancies in parts of the website
Tested through:
- specifying a center help URL and seeing the button appear, and not specifying one and seeing the navbar without the button
- removing a user from both a project and an allocation and reading the alert
- checking the default center name in config settings and in parts of the frontend, such as when requesting an allocation
=> Miscellaneous config issues fixed

coldfront/core/allocation/signals.py
https://stackoverflow.com/questions/70364068/django-cms-unexpected-keyword-argument-providing-args
=> Arguments in signal definitions are obsolete

coldfront/core/allocation/templates/allocation/allocation_request_list.html
Resolves #415 — Now, regardless of whether an allocation has attributes set or not, the text displayed on the button is "Activate." Tests were performed by:
1. Logging in as a user
2. Creating multiple allocations
3. Changing the status of some allocations to a property other than "New"
4. Logging in as an admin
5. Setting attributes to one allocation without changing its status
6. Checking that the allocation request button reads "Activate" and activating the allocation
7. Checking that the status of this allocation is "Active" and the expiration date is set to 365 days out
8. Going back to the allocation requests and checking that the request with no attributes has a button reading "Activate" rather than "Approve"
9. Making sure that the user is prompted by an alert to confirm this …
=> Correct text now displayed on "Activate" button for allocation requests without attributes set

.gitignore, coldfront/core/allocation/management/commands/add_allocation_defaults.py, coldfront/plugins/xdmod/management/commands/xdmod_usage.py, coldfront/plugins/xdmod/utils.py
This will import GPUh and GB to respective metrics from XDMOD instance. It was tested against our XDMOD, but please be careful. 
Additional argument for xdmod_usage will import metrics for expired allocations - useful for new/migrated setups.
=> Add GPUh and Storage metrics support for XDMOD import

coldfront/core/allocation/models.py
This was preventing edits in DjangoAdmin - its ok have unique attribute in form as long as it is the existing one.
=> Update Allocation models.py

coldfront/core/allocation/views.py, coldfront/templates/email/allocation_activated.txt, coldfront/templates/email/allocation_change_approved.txt, coldfront/templates/email/allocation_change_denied.txt, coldfront/templates/email/allocation_revoked.txt
Resolves issue #474 — Now, allocations that have been given a revoked status display a similar behavior to an allocation that has been marked as denied, sending an email to the user and signaling that the allocation should be disabled. Newlines are also added to email templates to enhance readability.
=> Signal fixed on changing allocation statuses

coldfront/core/allocation/signals.py, coldfront/core/allocation/views.py
This allows centers to write their own plugins that allows for a small task to be done when an allocation is created. For example, automatically assigning certain allocation attributes: when a new allocation request for slurm resource is created, a plugin could read this signal and automatically assign the `slurm_account_name` attribute based on project name and allocation id.
=> Add signal for new allocation requests.

docs/pages/config.md
=>  Mention collectstatic for "SITE_STATIC" usage

coldfront/plugins/mokey_oidc/README.md
I had an issue with using `mozilla-django-oidc` was that the user would log in with OIDC, get redirected to our provider, but ultimately get returned to the login failure url (`/` by default) and not get logged in. The problem was that the `sessionid` cookie was not getting returned to us in Firefox, because the `SESSION_COOKIE_SAMESITE` setting is set to `"Strict"` in ColdFront's default settings in `auth.py`.
I fixed the problem by changing the setting to `"Lax"`.
Also removed an extra newline at the start of the code block.
=> Update mokey_oidc readme to include OIDC configuration without Mokey/Hydra integration

.gitignore, coldfront/core/grant/forms.py, coldfront/core/grant/models.py, coldfront/core/grant/templates/grant/grant_report_list.html, coldfront/core/project/templates/project/project_detail.html
Resolves issue #442 — Grant amounts in the grant creation/ editing form can now be entered with dollar signs and commas, and percents can be entered with percent signs. In the grant report and project detail pages, grant amounts and percentages are also formatted to be rounded to two decimal places for consistency.
=> Grants formatting error fixed

docs/pages/config.md
I had to jump through some hoops to get Coldfront's LDAP authentication working against Active Directory. I believe these extra examples in the documentation could be useful to other institutions who run into the same issues I did.
=> Adding additional advanced documentation.

coldfront/config/core.py, coldfront/config/urls.py, coldfront/core/portal/templates/portal/center_summary.html, coldfront/core/project/templates/project/project_detail.html, coldfront/core/project/templates/project/project_review.html, coldfront/core/project/templates/project/project_review_email.html, coldfront/core/project/templates/project/project_review_list.html, coldfront/core/project/urls.py, coldfront/core/project/views.py, coldfront/templates/common/navbar_admin.html, coldfront/templates/common/navbar_director.html, coldfront/templates/common/navbar_nonadmin_staff.html, docs/pages/config.md
Fixes #507 
Users can now toggle whether or not they would like grant, publication, and research output functionality by setting the following config options:
- RESEARCH_OUTPUT_ENABLE (True or False)
- GRANT_ENABLE (True or False)
- PUBLICATION_ENABLE (True or False)
To avoid conflicts while reenabling, these apps are installed by default, but if a user sets the config option to False for any of the above, it removes all functionality from the frontend.
=> Add option to disable grants, publications, and research outputs

docs/pages/config.md
Whilst setting up OIDC auth with Coldfront I ran into this issue. SESSION\_COOKIE\_SAMESITE is set to "strict" in `coldfrotn/config/auth.py`. This doesn't play nicely as with OIDC however as mozilla\_django\_oidc uses anonmyous sessions to store state for the authentication requst. The strict setting prevents the session cookie from being included upon redirects from the IDP preventing verification of the state data.
This requirement is mentioned in the README for the mokey plugin but this PR adds the info into the configuration section of the docs for better discoverability.
=> Document required SESSION_COOKIE_SAMESITE setting for OIDC auth

coldfront/config/plugins/openid.py
`MOKEY_OIDC_PI_GROUP` is currently not picked up form the configuration environment variable.
=> OIDC config: set `MOKEY_OIDC_PI_GROUP` from env var

coldfront/core/allocation/templates/allocation/allocation_request_list.html, coldfront/core/allocation/views.py
Fixes #647. This loops through the history of an allocation with the status "Renewal Requested" from latest to earliest and finds the date of the history with the first "Renewal Requested" status. Since it loops from latest to earliest it will always grab the date of the latest renewal request.
=> Fixes the bug in ubccr#647

coldfront/core/allocation/views.py, coldfront/core/resource/management/commands/add_resource_defaults.py
This PR adds the ability to set a limit on the number of allocations a resource can have in a project. This is set by creating a new 
`allocation_limit` resource attribute for a resource with the number you want to limit the resource to. It will prevent users from submitting a new allocation request for that resource if the limit is reached. This limit applies to all projects for that resource. This partially handles #659.
=> Adds allocation limits for a resource

coldfront/core/allocation/signals.py, coldfront/core/allocation/views.py
For our cloud service at the MOC, we have a use case where it is important to know when an allocation change request has been created, not just when it was approved.
=> Added a signal for when allocation change requests are created

coldfront/core/allocation/views.py
The if statement used the wrong operator to determine if the allocation status was changed to "Denied" or "Revoked". This prevented a signal from being sent that would indicated that the allocation should be disabled.
=> Fixed a bug that prevented allocations from being disabled even after it has been denied or revoked

coldfront/core/project/forms.py, coldfront/core/project/views.py
**Reason**
Project creation is an essential feature and it may be expected for the associated fields to change over time. Currently, if sites wish to alter the associated fields then the `view.py` class must be changed itself, arguably creating issues with readability, maintenance and overpopulating the view class with form fields. 
**Changes made**
- Removing project creation fields and redirecting to a form class
- Implementing project form class.
=> Adding ProjectCreateView fields into dedicated form class. 

coldfront/core/project/views.py
The Project signal for project_new needs to be at the end. So that any additional features such as project code can get captured.
This PR simply moves its position in core/views.py
=> Reposition project_new signal (to end) in core/views.py

.github/ISSUE_TEMPLATE/bug-fix.yml
Modified the bug-fix.yml file so that the entry area for the version number is now a generic input text box instead of a selector with only a limited number of versions. Closes #691
=> Changed the version to type: input

coldfront/config/logging.py, coldfront/core/attribute_expansion.py, coldfront/core/utils/common.py, coldfront/plugins/freeipa/management/commands/freeipa_check.py, coldfront/plugins/freeipa/management/commands/freeipa_expire_users.py, coldfront/plugins/freeipa/tasks.py, coldfront/plugins/mokey_oidc/auth.py, coldfront/plugins/slurm/management/commands/slurm_check.py, coldfront/plugins/slurm/management/commands/slurm_dump.py, coldfront/plugins/slurm/utils.py, coldfront/plugins/xdmod/management/commands/xdmod_usage.py
Replaced all instances of logging.WARN with logging.WARNING and logging.warn with logging.warning. This ensures that coldfront will not break due to using deprecated functions which were removed in Python 3.13 and greater.
=> Refactored deprecated logging module functionality

coldfront/core/allocation/models.py
1. Start a ColdFront container with a new database
2. Execute the following commands to get the deployment configured:
1. Execute initial_setup script
2. Execute the load_test_data command
3. Create a new superuser and name it 'changeme'
3. Navigate the the webpage and log in as 'changeme'
4. Go to Admin -> All Allocations -> select the allocation with ID==1
5. Go to Allocation Attributes -> Add Allocation Attribute
1. Specify an AllocationAttribute type that is included in the setting ALLOCATION_ATTRIBUTE_VIEW_LIST. By default this includes ["slurm_account_name", "freeipa_group", "Cloud Account Name"].
2. Set the value to `<b>This is where the text is.<b> <script>alert("Malicious ! slurm ! Script")</script>`.
6. Navigate to Admin -> All Projects -> ID==1
1. The malicious script should …
=> Remediated mark_safe calls to prevent XSS attacks.

coldfront/core/allocation/forms.py, coldfront/core/allocation/signals.py, coldfront/core/allocation/templates/allocation/allocation_allocationattribute_delete.html, coldfront/core/allocation/templates/allocation/allocation_attribute_edit.html, coldfront/core/allocation/templates/allocation/allocation_detail.html, coldfront/core/allocation/tests/test_views.py, coldfront/core/allocation/urls.py, coldfront/core/allocation/views.py
This PR adds a page that allows admins to edit allocation attributes and a button on the Allocation Detail page to access this page, which would close #672.
This PR also adds a signal for allocation attribute changes, which is sent when Allocation Change Requests are approved and through this page, which should [help] close #293.
=>  Add an Allocation Attribute Edit Page

docs/pages/config.md
```
Traceback (most recent call last):
File "/srv/simon/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/simon/venv/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
return self.cursor.execute(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/simon/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
res = self._query(mogrified_query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/simon/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
db.query(q)
^^^^^^^^^^^
File "/srv/simon/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
_mysql.connection.query(self, query) …
```
=> document project code max length
